# PyTorch 是什么

它是一个基于Python的科学计算包，目标用户有两类
- 为了使用GPU来替代numpy
- 一个深度学习援救平台：提供最大的灵活性和速度

## 开始

### 张量（Tensors)

张量类似于numpy的ndarrays，不同之处在于张量可以使用GPU来加快计算。

In [31]:
from __future__ import print_function
import torch

构建一个未初始化的5*3的矩阵：

In [32]:
x = torch.empty(5, 3)
print(x)

tensor([[ 2.5783e-25,  4.5751e-41,  1.1321e-37],
        [ 0.0000e+00, -1.4320e+32,  4.5750e-41],
        [-3.6926e+14,  4.5750e-41, -1.4634e+32],
        [ 4.5750e-41, -3.0062e+33,  4.5750e-41],
        [ 1.3563e-19,  1.3563e-19,  0.0000e+00]])


构建一个随机初始化的矩阵

In [33]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.9028,  0.5983,  0.8612],
        [ 0.5322,  0.4551,  0.8155],
        [ 0.5321,  0.0608,  0.8242],
        [ 0.7611,  0.3642,  0.0165],
        [ 0.6021,  0.3890,  0.8743]])


构建一个dtype是长整形的零矩阵

In [35]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


直接从数据中创建一个tensor

In [36]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


或者根据一个已有的tensor来创建一个新的tensor。除非用户提供新的值，否则这些方法会重用输入张量的属性，例如：dtype

In [37]:
x = x.new_ones(5, 3, dtype = torch.double)   #新方法会采用大小
print(x)

x = torch.randn_like(x, dtype = torch.float) #重写dtype！
print(x)                                     #结果有相同大小

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-0.3894,  0.4259,  1.3997],
        [ 0.1361,  0.2254,  1.2841],
        [-2.6795,  0.9728,  0.6610],
        [-0.2451,  0.1899, -0.4199],
        [ 1.5420, -1.9392, -0.2476]])


获取矩阵的大小

In [38]:
print(x.size())

torch.Size([5, 3])


**！注意：**
`torch.Size`实际上是一个元组，所以它支持元组相同的操作。

### 操作

张量上的操作有多重语法形式，下面我们一加法为例进行讲解。

加法：语法1

In [39]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3006,  0.5100,  1.7248],
        [ 1.0010,  0.6341,  1.8629],
        [-2.0656,  1.8772,  1.0689],
        [-0.1068,  0.5903, -0.3870],
        [ 1.8539, -1.7715, -0.2332]])


加法：语法2

In [40]:
print(torch.add(x, y))

tensor([[ 0.3006,  0.5100,  1.7248],
        [ 1.0010,  0.6341,  1.8629],
        [-2.0656,  1.8772,  1.0689],
        [-0.1068,  0.5903, -0.3870],
        [ 1.8539, -1.7715, -0.2332]])


加法：给出一个输出张量作为参数

In [41]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.3006,  0.5100,  1.7248],
        [ 1.0010,  0.6341,  1.8629],
        [-2.0656,  1.8772,  1.0689],
        [-0.1068,  0.5903, -0.3870],
        [ 1.8539, -1.7715, -0.2332]])


加法：原地(in-place)

In [42]:
y.add_(x)
print(y)

tensor([[ 0.3006,  0.5100,  1.7248],
        [ 1.0010,  0.6341,  1.8629],
        [-2.0656,  1.8772,  1.0689],
        [-0.1068,  0.5903, -0.3870],
        [ 1.8539, -1.7715, -0.2332]])


**！注意：**
任何使就地调整张量的操作都用`_`进行后置固定。 例如：` x.copy_(y), x.t_()`，将改变`x`。

你可以使用标准的NumPy索引操作！

In [43]:
print(x[:, -1])

tensor([ 1.3997,  1.2841,  0.6610, -0.4199, -0.2476])


调整大小：如果要调整大小/形状，可以使用`torch.view`：

In [44]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1代表从其他demension推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个元素张量，可使用`.item()`将值作为Python的数值类型

In [45]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2316])
-1.2316290140151978


**稍后阅读：**

[这里](http://pytorch.org/docs/torch)描述了100多个张量运算，包括转置，索引，切片，数学运算，线性代数，随机数等。

## numpy桥

把一个torch张量转换为numpy数组或者反过来都是很简单的。

Torch张量和numpy数组将共享潜在的内存，改变其中一个也将改变另一个。

### 把Torch张量转换为numpy数组

In [46]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [47]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


看一下numpy数组的值如何在改变。

In [48]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### 把numpy数组转换为torch张量

看看改变numpy数组如何自动改变torch张量。

In [50]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


所有在CPU上的张量，除了字符张量，都支持在numpy之间转换。

## CUDA张量

可以使用`.to`方法将张量移动到任何设备上。

In [51]:
#只在CUDA可用的情况下运行这个cell
#我们将使用``torch.device``对象将张量移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda") #一个CUDA设备对象
    y = torch.ones_like(x, device = device) #直接在GPU上创建张量
    x = x.to(device) #或者只是用来字符串``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) #``.to``也可以一起改变dtype！

tensor([-0.2316], device='cuda:0')
tensor([-0.2316], dtype=torch.float64)


**脚本总运行时间:**(0分0.014秒) 

ps 我没尝试这里

下载python源码：[tensor_tutorial.py](https://pytorch.org/tutorials/_downloads/tensor_tutorial.py)

下载jupyter notebook：[tensor_tutorial.ipynb](https://pytorch.org/tutorials/_downloads/tensor_tutorial.ipynb)

中文版：[tensor_tutorial_CN.ipynb](https://github.com/Marvae/pytorch-tutorials-CN/blob/master/tensor_tutorial_CN.ipynb)